services:
  go_chat:
    container_name: go_chat
    image: golang
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      - cache_db
      - amqp
  amqp:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  go_db:
    container_name: go_db
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  cache_db:
    container_name: cache_db
    image: redis:alpine
    env_file:
      - ./.env
    ports:
      - '6379:6379'
volumes:  
  pgdata: {}
