SELECT 'CREATE DATABASE go_chat'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'go_chat')\gexec
\c go_chat;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "CHAT" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  SENDER_ID VARCHAR(255) NOT NULL,
  RECEIVER_ID VARCHAR(255) NOT NULL,
  MESSAGE TEXT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "USER" (
  ID VARCHAR(255) NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL
);
