package constants

const (
	RABBITMQ_HOST = "RABBITMQ_HOST"
	SERVER_PORT   = "SERVER_PORT"
	SERVER_HOST   = "SERVER_HOST"
	ENV           = "ENV"

	REDIS_HOST     = "REDIS_HOST"
	REDIS_PORT     = "REDIS_PORT"
	REDIS_PASSWORD = "REDIS_PASSWORD"

	POSTGRES_HOST     = "POSTGRES_HOST"
	POSTGRES_PORT     = "POSTGRES_PORT"
	POSTGRES_USER     = "POSTGRES_USER"
	POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
	POSTGRES_NAME     = "POSTGRES_NAME"
)
